version: '2'
services:
  bilbot-php:
    build: ./src/bilbot-php
    #ports:
     #- "80:80"
    environment:
     - RAILS_ENV=staging
    volumes:
     - ./src/bilbot-php/www:/var/www/html
     - ./vendor:/var/www/html/vendor
    links:
      - bilbot-mysql
      - watson-php
  bilbot-mysql:
    image: mysql
    ports:
     - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: bilbot
      MYSQL_USER: puppy
      MYSQL_PASSWORD: 1234
    volumes:
      - ./src/bilbot-mysql/structure.sql:/docker-entrypoint-initdb.d/structure.sql
  watson-php:
    build: ./src/bilbot-watson
    volumes:
      - ./src/bilbot-watson:/var/www/docker-symfony
    environment:
      XDEBUG_CONFIG: remote_host=192.168.99.1
      PHP_IDE_CONFIG: serverName=docker-symfony
  watson-nginx:
    image: nginx:1.9.10
    links:
      - watson-php
    volumes_from:
      - watson-php
    volumes:
      - ./src/bilbot-watson/docker/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"