api_test_name:
  path: /test
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Test:execute

understandme:
  path: /understandme
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Gateway:understandMe

agenda_analysis:
  path: /agenda_analysis
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Gateway:agendaAnalysis