api_test_name:
  path: /test
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Test:execute

# Clubs
clubs_debug:
  path: /clubs_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Clubs:debug

clubs_detail:
  path: /clubs_detail
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Clubs:detail

clubs_search:
  path: /clubs_search
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Clubs:search

clubs_list:
  path: /clubs_list
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Clubs:list
# Agenda
agenda_debug:
  path: /agenda_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Agenda:debug

agenda_search:
  path: /agenda_search
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Agenda:search

agenda_list:
  path: /agenda_list
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Agenda:list

agenda_detail:
  path: /agenda_detail
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Agenda:detail
# Restaurants
restaurants_debug:
  path: /restaurants_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Restaurants:debug

# Bikes
bikes_debug:
  path: /bikes_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Bikes:debug

bikes_search:
  path: /bikes_search
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Bikes:search

bikes_list:
  path: /bikes_list
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Bikes:list

bikes_detail:
  path: /bikes_detail
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Bikes:detail

bikes_near_point:
  path: /bikes_near_point
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Bikes:nearPoint

# Buses per route
buses_per_route_debug:
  path: /buses_per_route_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/BusesPerRoute:debug

# Bus stops
bus_stops_debug:
  path: /bus_stops_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/BusStops:debug

# Nightly bus routes
nightly_bus_routes_debug:
  path: /nightly_bus_routes_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/NightlyBusRoutes:debug

# Daily bus routes
daily_bus_routes_debug:
  path: /daily_bus_routes_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/DailyBusRoutes:debug

# Tourist Offices
tourist_offices_debug:
  path: /tourist_offices_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/TouristOffices:debug

# Tourist attractions
tourist_attractions_debug:
  path: /tourist_attractions_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/TouristAttractions:debug

# Hotels
hotels_debug:
  path: /hotels_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Hotels:debug

# Portals
portals_debug:
  path: /portals_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Portals:debug