api_test_name:
  path: /test
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Test:execute

# Clubs
clubs_debug:
  path: /clubs_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Clubs:debug


# Agenda
agenda_debug:
  path: /agenda_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Agenda:debug

# Restaurants
restaurants_debug:
  path: /restaurants_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Restaurants:debug

# Bikes
bikes_debug:
  path: /bikes_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Bikes:debug

# Buses per route
buses_per_route_debug:
  path: /buses_per_route_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/BusesPerRoute:debug

# Bus stops
bus_stops_debug:
  path: /bus_stops_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/BusStops:debug

# Nightly bus routes
nightly_bus_routes_debug:
  path: /nightly_bus_routes_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/NightlyBusRoutes:debug

# Daily bus routes
daily_bus_routes_debug:
  path: /daily_bus_routes_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/DailyBusRoutes:debug

# Tourist Offices
tourist_offices_debug:
  path: /tourist_offices_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/TouristOffices:debug

# Tourist attractions
tourist_attractions_debug:
  path: /tourist_attractions_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/TouristAttractions:debug

# Hotels
hotels_debug:
  path: /hotels_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Hotels:debug

# Portals
portals_debug:
  path: /portals_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Portals:debug