api_test_name:
  path: /test
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Test:execute

bilbaoclubs:
  path: /bilbaoclubs
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Gateway:bilbaoClubs
