api_test_name:
  path: /test
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Test:execute

# Clubs
clubs_debug:
  path: /clubs_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Clubs:debug

clubs_detail:
  path: /clubs_detail
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Clubs:detail

clubs_search:
  path: /clubs_search
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Clubs:search

clubs_list:
  path: /clubs_list
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Clubs:list
# Agenda
agenda_debug:
  path: /agenda_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Agenda:debug

agenda_search:
  path: /agenda_search
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Agenda:search

agenda_list:
  path: /agenda_list
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Agenda:list

agenda_detail:
  path: /agenda_detail
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Agenda:detail

# Restaurants
restaurants_debug:
  path: /restaurants_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Restaurants:debug

restaurants_search:
  path: /restaurants_search
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Restaurants:search

restaurants_list:
  path: /restaurants_list
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Restaurants:list

restaurants_detail:
  path: /restaurants_detail
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Restaurants:detail

# Bikes
bikes_debug:
  path: /bikes_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Bikes:debug

bikes_search:
  path: /bikes_search
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Bikes:search

bikes_list:
  path: /bikes_list
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Bikes:list

bikes_detail:
  path: /bikes_detail
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Bikes:detail

bikes_near_point:
  path: /bikes_near_point
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Bikes:nearPoint

# Tourist Offices
tourist_offices_debug:
  path: /tourist_offices_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/TouristOffices:debug

tourist_offices_search:
  path: /tourist_offices_search
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/TouristOffices:search

tourist_offices_list:
  path: /tourist_offices_list
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/TouristOffices:list

tourist_offices_detail:
  path: /tourist_offices_detail
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/TouristOffices:detail

# Tourist attractions
tourist_attractions_debug:
  path: /tourist_attractions_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/TouristAttractions:debug

tourist_attractions_search:
  path: /tourist_attractions_search
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/TouristAttractions:search

tourist_attractions_list:
  path: /tourist_attractions_list
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/TouristAttractions:list

tourist_attractions_detail:
  path: /tourist_attractions_detail
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/TouristAttractions:detail

# Hotels
hotels_debug:
  path: /hotels_debug
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Hotels:debug

hotels_search:
  path: /hotels_search
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Hotels:search

hotels_list:
  path: /hotels_list
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Hotels:list

hotels_detail:
  path: /hotels_detail
  methods: [GET]
  requirements:
      _format: json
  defaults:
      _format: json
      _controller: AppBundle:REST/Hotels:detail